language: objective-c
osx_image: xcode10
cache: bundler
env:
  global:
  - FRAMEWORK_PROJECT=CTPanoramaView.xcodeproj
  - FRAMEWORK_SCHEME=CTPanoramaView
  - EXAMPLE_PROJECT="Example/Example.xcodeproj"
  - EXAMPLE_SCHEME=Example
  - SDK=iphonesimulator12.0
  matrix:
  - DESTINATION="OS=12.0,name=iPhone 8"    RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
  - DESTINATION="OS=11.4,name=iPhone 6s"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
  - DESTINATION="OS=8.4,name=iPhone 5"    RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework and Run Testsif specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$FRAMEWORK_PROJECT" -scheme "$FRAMEWORK_SCHEME" -sdk "$SDK" -destination "$DESTINATION", ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    fi

  # Build Example if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -project "$EXAMPLE_PROJECT" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION", ONLY_ACTIVE_ARCH=NO | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi